import type { Metadata } from "next";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify"; // Import ToastContainer
import "react-toastify/dist/ReactToastify.css"; // Import toast styles
import Header from "./components/Header";
import SideBar from "./components/SideBar";
import SubHeader from "./components/SubHeader";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Movie Hunt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col md:flex-row min-h-screen md:px-[60px] lg:px-[70px] xl:px-[80px]">
          <div className="md:w-64 md:flex-shrink-0">
            <SideBar />
          </div>

          <div className="flex-1">
            <Header />
            <SubHeader />
            <main className="sm:p-4 md:p-[0px]">{children}</main>
          </div>
        </div>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          closeOnClick
          draggable
          pauseOnHover
        />
      </body>
    </html>
  );
}
